language: node_js
node_js:
- node
services: mongodb
cache:
  directories:
  - node_modules
install:
- npm install
branches:
  only:
  - master
  - development
script:
- sleep 5
before_deploy:
- mkdir dist
- echo "Building client distribution."
- cd client
- npm i
- npm run build
- cd ..
- echo "Finished building client distribution."
- echo "Building server distribution."
- cd server
- npm i
- npm run build
- zip -r server.zip dist package.json .env-cmdrc .ebextensions
- cd ..
- echo "Finished building server distribution."
deploy:
  - provider: s3
    access_key_id: AKIAIVBBZFN7NFRWONSQ
    secret_access_key: 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
    bucket: campfire-stories
    skip_cleanup: true
    region: us-east-1
    local_dir: client/build
    on:
      branch: master
  - provider: elasticbeanstalk
    skip_cleanup: true
    zip_file: server/server.zip
    access_key_id:
    secret_access_key: ZbQ1R+4j6XXBfqZIrZDWEhKMF/Xs5gw8kkJX2p54
    region: us-east-1
    app: campfire-stories
    env: projects
    bucket_name: elasticbeanstalk-us-east-1-812452178264
    on:
      branch: master
notifications:
  email:
    recipients:
    - hansen.mmb@gmail.com
    on_success: always
    on_failure: always
