language: node_js
node_js:
- node
services: mongodb
cache:
  directories:
  - node_modules
install:
- npm install
branches:
  only:
  - master
  - development
script:
- sleep 5
before_deploy:
- mkdir dist
- echo "Building client distribution."
- cd client
- npm i
- npm run build
- cd ..
- echo "Finished building client distribution."
- echo "Building server distribution."
- cd server
- npm i
- npm run build
- zip server.zip dist package.json .env-cmdrc .ebextensions
- cd ..
- echo "Finished building server distribution."
deploy:
  - provider: s3
    access_key_id:
      secure: ZlYKkUsfBz9o2nMDeYKRVn2QQlAbVUveR8EiLLsh9AxIOARUk0pB0hrTPlMJ1l81pwgylxxmDB897pwG2w0Cc0tAeBWOTekw5JTpxW5axaRXejAEMlakKdkli2XJTBXVDIPDT8Q6Hr/ZMgcGRzxoFqbS1/g4tsxyB9SOStgayYFaAESBcLywmJBahTeM3sW8ebGCdTX3SRjw7Ve5Bfuf42Hm3gye4D0cfwdSRA3YcaYyhiCSQLlVznDWGRteVeq5Fr1joaYCGO8L3qOp0gNTttOIDebIA3RorfNXC4ye1Jd3YyreUq/gt4ebMmGFceTFpbxZdP5B2z/mdYKMZz7prqTxiSTlJ8aoGAPzUx19Wl6qwgsLDgUbSq8Rcn+oueINBN+ozkYIXoUO/5kbWY2yaKJaa5MTKHBu9pwG3CTth4opGrphCPHjJgaFaAN3spNiJVeVYckBc0iCk88gRr39ihOLdii7EkAj7P5FaRt0mTy9S49bWRb3yTyuErAqmsHexkGAuVfVnXKTgnl9h9Bfepp9OQElgvQzCuzd9k40R+jH2XButGgitCUZn63XJywiHuExMKHzenGxf9TK3EfmbAvDLKj3iP0MFseNmvCyq4IMluQxQet5leLKIymC8u1T+yaMdZtcSc3ys5L5l03wiaFF/QlRJg6UeR/b5lzDVNo=
    secret_access_key:
      secure: 9Tady/bXtvzwZ+c/jjWSnFC2iozYLVc5+Jhd65ZE5QYI/t87qfbLoj0qE6Gh1Y431Rem56FYjd9NU5XnZfdqwFO1cFPFJtWWZYdr47UAvvAHuR1oFTpdG+WQJezXd0KGaS5VBTp6g3WkrZrjWyLeVEfRz0QJAWtb3PJ1TSBlMGZ0BwpwUWJazrYOYkUnnyAipo7VciuWqFJB4l12jsYemIc3SpJVHVJfIcLnNf4Wz2wtdTklcbjtlIeXlmP3q6l0zYyT6AZWU+xUQWdWhvVjE+nFUqN+KyxH6MLlKYgqrKllnLCEkF+8yEmOhjUv6YVHuQMp3sO4LEDwUbkuXJVoEAtKAR7k+SfX8Afu7MK+kegdjNzN+fpNW5frab/1yor0vT/aYpTQBoIILWzvFcnx85zLLRPOqRiUYhFxwsOaayucmyoXtT37cGP7j0OtLmgEPlgM0SFoZN1WN+vfgXQ+iKOwnIZWB7q80vnl06FhpTLziHLo0soCZGwHcg9FU7BmX4bWifGR0Em/NxTyZnvZ32x3L4rrwgQN+fQQxOZCe8V6OJ+ABP8jzQI6gAfUq+tkpnefN7slcb+Q9RRzMe1wYhM2FCmM08QWjoofybUEH3kUqTtc3OBxxY71IEe1qKSnMUks7IXgKjut0YpBqN6zX8kfLN4jkrTUoCnbSVdVr20=
    bucket: campfire-stories
    skip_cleanup: true
    region: us-east-1
    local_dir: client/build
    on:
      branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  zip_file: server/server.zip
  access_key_id:
    secure: ZlYKkUsfBz9o2nMDeYKRVn2QQlAbVUveR8EiLLsh9AxIOARUk0pB0hrTPlMJ1l81pwgylxxmDB897pwG2w0Cc0tAeBWOTekw5JTpxW5axaRXejAEMlakKdkli2XJTBXVDIPDT8Q6Hr/ZMgcGRzxoFqbS1/g4tsxyB9SOStgayYFaAESBcLywmJBahTeM3sW8ebGCdTX3SRjw7Ve5Bfuf42Hm3gye4D0cfwdSRA3YcaYyhiCSQLlVznDWGRteVeq5Fr1joaYCGO8L3qOp0gNTttOIDebIA3RorfNXC4ye1Jd3YyreUq/gt4ebMmGFceTFpbxZdP5B2z/mdYKMZz7prqTxiSTlJ8aoGAPzUx19Wl6qwgsLDgUbSq8Rcn+oueINBN+ozkYIXoUO/5kbWY2yaKJaa5MTKHBu9pwG3CTth4opGrphCPHjJgaFaAN3spNiJVeVYckBc0iCk88gRr39ihOLdii7EkAj7P5FaRt0mTy9S49bWRb3yTyuErAqmsHexkGAuVfVnXKTgnl9h9Bfepp9OQElgvQzCuzd9k40R+jH2XButGgitCUZn63XJywiHuExMKHzenGxf9TK3EfmbAvDLKj3iP0MFseNmvCyq4IMluQxQet5leLKIymC8u1T+yaMdZtcSc3ys5L5l03wiaFF/QlRJg6UeR/b5lzDVNo=
  secret_access_key:
  secure: 9Tady/bXtvzwZ+c/jjWSnFC2iozYLVc5+Jhd65ZE5QYI/t87qfbLoj0qE6Gh1Y431Rem56FYjd9NU5XnZfdqwFO1cFPFJtWWZYdr47UAvvAHuR1oFTpdG+WQJezXd0KGaS5VBTp6g3WkrZrjWyLeVEfRz0QJAWtb3PJ1TSBlMGZ0BwpwUWJazrYOYkUnnyAipo7VciuWqFJB4l12jsYemIc3SpJVHVJfIcLnNf4Wz2wtdTklcbjtlIeXlmP3q6l0zYyT6AZWU+xUQWdWhvVjE+nFUqN+KyxH6MLlKYgqrKllnLCEkF+8yEmOhjUv6YVHuQMp3sO4LEDwUbkuXJVoEAtKAR7k+SfX8Afu7MK+kegdjNzN+fpNW5frab/1yor0vT/aYpTQBoIILWzvFcnx85zLLRPOqRiUYhFxwsOaayucmyoXtT37cGP7j0OtLmgEPlgM0SFoZN1WN+vfgXQ+iKOwnIZWB7q80vnl06FhpTLziHLo0soCZGwHcg9FU7BmX4bWifGR0Em/NxTyZnvZ32x3L4rrwgQN+fQQxOZCe8V6OJ+ABP8jzQI6gAfUq+tkpnefN7slcb+Q9RRzMe1wYhM2FCmM08QWjoofybUEH3kUqTtc3OBxxY71IEe1qKSnMUks7IXgKjut0YpBqN6zX8kfLN4jkrTUoCnbSVdVr20=
  region: us-east-1
  app: campfire-stories
  env: projects
  bucket_name: elasticbeanstalk-us-east-1-812452178264
  on:
    branch: master
notifications:
  email:
    recipients:
    - hansen.mmb@gmail.com
    on_success: always
    on_failure: always
