language: node_js
node_js:
- node
services: mongodb
cache:
  directories:
  - node_modules
install:
- npm install
branches:
  only:
  - master
  - development
script:
- sleep 5
before_deploy:
- mkdir dist
- echo "Building client distribution."
- cd client
- npm i
- npm run build
- cd ..
- echo "Finished building client distribution."
- echo "Building server distribution."
- cd server
- npm i
- npm run build
- zip server.zip dist package.json .env-cmdrc .ebextensions
- cd ..
- echo "Finished building server distribution."
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  zip_file: server/server.zip
  access_key_id:
      - secure:
        +Wxa0+pXZFqt4J5UUtbzNTPMsvRd97wi3L1zBjFRzVXkGd3jhHPJsUNG36E+2Mb5zNJq+zbAQts90GoE/AKMf4bbVtHinvtyzyTgaFTJIR+N28DXAEAqfnTuzpTUJPn//uAKRvGdCWU4RKcjyhfxaZTDPdm81eb72xwemSLGFc8z0K8ERrYUnYZsDykAUubQdmsmdh+0izOEhiNn1DNy/4EbXrQg/n2CXxTM1hM6ssx8KfWv70t9dDuIraq0EaWAwoWK83pzRXIbB3H2PrQk/MVsd2QPgVGf1YbX4rdicVAMX2goLMA6apb1qq89typBl9I212c8Zdv5Mi1uGPJzwdtS2ZjCKJv1ACfj2HWPKaeKz3zOXUZ4Llp74l/7yTtImBujCg2qHetD/T/vGaOBEgQVPdSBBD7/srZCVAY2Y2IHMBsDeQTIDv12TckOTQeqIp3QBhiRlqsIlnrvQwuiBbGhhsqhgpy6W6To11zMEZpzQ83WP1K2lYHb4VvY0aZYNcg5K0A6CH9y2w3P3BZE/1Jkns5A1uuta+AmE8fy1Gj2yPIBUKAV/nzGPRDG0Yil8aom6CWgs6i8YPOHFy7+DhoKDx9l9GEMrYj/9wa2SDXA44GP48lZUoKl4u5SADj6dBho91Z+IZiTVR+tHw1gIH4aQd1DNgfDyTc2m6icsy0=
  secret_access_key:
    - secure:
      4nnTvKPYBLt73GI7lU2kN/Zqy53KmsaX5kiEV4vg38rim8tSZcv9KHsA8wg8Y1mb0T0h6LuoOBBCSEiNZ4eYWbieQwJ3gahCGB98wQEaThdaLoApo2pqwEztnSGFX6jFPTcT5gDyxJLzPvl/yX/MNJjuaEP6OQP3bAp9EMt7yHLUU8ru7uhXdnmtE5xqH15Fx9/jdWyWwzq7vLPL/2JI4EWhqZcBjsxgExt1nzZzPNVq7xxsvUaefsIOebABwsGpVoSBdf1fM5pwN1MezmklUIdgshg7kiomeL/tiXxf3YIMGDnKRjz8vObqP9VnO8VLD3noAli1JYNcknxnijSrwCKYYtY4iixER3Q0DtULdFdJF+Kz7eIpQ0aOacNrhV3Ign14x2AkdI56UZWT/rmReL5bP5Qwsi8McKDDunFTJEKeTybv3qvklfIIVCnnBO1Rsz3frJ9nvIZUDtEkhTNnFEuoUqP8iRZOZNbiqVJdmvN6IfyMVDttWIVixy8jX5+sUvnu66pt3kPF0sgDc++SYMV+XzVY+Wu4RyUvz0bBQ5EfLvBj6hJmQsTGmGO4HljkNQEE25hV01FvJA24RlWqTcJJzP9S7Wi0Vv1tt0Pm/4uXFS9JiOcaY4RyoujufyWSEydBqn1757qIdar2Qr0e3orrQ7CUU3MLVTzn7Hf9Wu0=
  region: us-east-1
  app: campfire-stories
  env: projects
  bucket_name: elasticbeanstalk-us-east-1-812452178264
  on:
    branch: master
- provider: s3
  access_key_id:
      - secure:
        +Wxa0+pXZFqt4J5UUtbzNTPMsvRd97wi3L1zBjFRzVXkGd3jhHPJsUNG36E+2Mb5zNJq+zbAQts90GoE/AKMf4bbVtHinvtyzyTgaFTJIR+N28DXAEAqfnTuzpTUJPn//uAKRvGdCWU4RKcjyhfxaZTDPdm81eb72xwemSLGFc8z0K8ERrYUnYZsDykAUubQdmsmdh+0izOEhiNn1DNy/4EbXrQg/n2CXxTM1hM6ssx8KfWv70t9dDuIraq0EaWAwoWK83pzRXIbB3H2PrQk/MVsd2QPgVGf1YbX4rdicVAMX2goLMA6apb1qq89typBl9I212c8Zdv5Mi1uGPJzwdtS2ZjCKJv1ACfj2HWPKaeKz3zOXUZ4Llp74l/7yTtImBujCg2qHetD/T/vGaOBEgQVPdSBBD7/srZCVAY2Y2IHMBsDeQTIDv12TckOTQeqIp3QBhiRlqsIlnrvQwuiBbGhhsqhgpy6W6To11zMEZpzQ83WP1K2lYHb4VvY0aZYNcg5K0A6CH9y2w3P3BZE/1Jkns5A1uuta+AmE8fy1Gj2yPIBUKAV/nzGPRDG0Yil8aom6CWgs6i8YPOHFy7+DhoKDx9l9GEMrYj/9wa2SDXA44GP48lZUoKl4u5SADj6dBho91Z+IZiTVR+tHw1gIH4aQd1DNgfDyTc2m6icsy0=
  secret_access_key:
    - secure:
      4nnTvKPYBLt73GI7lU2kN/Zqy53KmsaX5kiEV4vg38rim8tSZcv9KHsA8wg8Y1mb0T0h6LuoOBBCSEiNZ4eYWbieQwJ3gahCGB98wQEaThdaLoApo2pqwEztnSGFX6jFPTcT5gDyxJLzPvl/yX/MNJjuaEP6OQP3bAp9EMt7yHLUU8ru7uhXdnmtE5xqH15Fx9/jdWyWwzq7vLPL/2JI4EWhqZcBjsxgExt1nzZzPNVq7xxsvUaefsIOebABwsGpVoSBdf1fM5pwN1MezmklUIdgshg7kiomeL/tiXxf3YIMGDnKRjz8vObqP9VnO8VLD3noAli1JYNcknxnijSrwCKYYtY4iixER3Q0DtULdFdJF+Kz7eIpQ0aOacNrhV3Ign14x2AkdI56UZWT/rmReL5bP5Qwsi8McKDDunFTJEKeTybv3qvklfIIVCnnBO1Rsz3frJ9nvIZUDtEkhTNnFEuoUqP8iRZOZNbiqVJdmvN6IfyMVDttWIVixy8jX5+sUvnu66pt3kPF0sgDc++SYMV+XzVY+Wu4RyUvz0bBQ5EfLvBj6hJmQsTGmGO4HljkNQEE25hV01FvJA24RlWqTcJJzP9S7Wi0Vv1tt0Pm/4uXFS9JiOcaY4RyoujufyWSEydBqn1757qIdar2Qr0e3orrQ7CUU3MLVTzn7Hf9Wu0=
  bucket: campfire-stories
  skip_cleanup: true
  region: us-east-1
  local_dir: client/build
  on:
    branch: master
notifications:
  email:
    recipients:
    - hansen.mmb@gmail.com
    on_success: always
    on_failure: always
